language: node_js
install:
  - npm install 
 
node_js:
  
cache:
  directories:
  - node_modules

branches:
  only:
    - master1
    - dev
script:
  - react-native run-android

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  local_dir: build
  keep-history: true
  on:
    branch: master

