install:
  - nvm install 11
  - npm install -g "npm@$(jq -r '.engines.npm' package.json)"
  - npm ci
matrix:
  include:
    - os: linux
      language: android
      jdk: oraclejdk8
      android:
        components:
          - build-tools-28.0.3
          - android-28
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
      before_install:
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.3"
      script:
        - "./android/gradlew assembleRelease -p android/" 
      cache:
        directories:
          - node_modules
